In [1]:
from keras.preprocessing import text 

C:\Users\yudai\anaconda3\envs\py38-gpu\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\yudai\anaconda3\envs\py38-gpu\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\yudai\anaconda3\envs\py38-gpu\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:\n%s" %


## Tokenizerのインスタンス化とfitting

In [2]:
texts = ["I have a pen.", "I have an apple", "You have pen and apple."] # 集計したい文字列のリスト
tokenizer = text.Tokenizer() # インスタンス化
tokenizer.fit_on_texts(texts) # fitting

## 文字列をシーケンス番号で出力
シーケンス番号は1から始まる整数で表される.

In [3]:
list_tokenized = tokenizer.texts_to_sequences(texts) # textをシーケンス番号で表す
print(list_tokenized)

[[2, 1, 5, 3], [2, 1, 6, 4], [7, 1, 3, 8, 4]]


In [5]:
from keras.preprocessing import sequence

# 配列の長さを固定長にする
list_sequence = sequence.pad_sequences(list_tokenized, maxlen=10)
print(list_sequence)

[[0 0 0 0 0 0 2 1 5 3]
 [0 0 0 0 0 0 2 1 6 4]
 [0 0 0 0 0 7 1 3 8 4]]
